const readbleArray = [
  { label: "ativo", readable: "Status" },
  { label: "ativo_not_visible", readable: "Status" },
  { label: "ativoReadOnly", readable: "Status" },
  { label: "categoria", readable: "Categoria" },
  { label: "categoriaServico", readable: "Categoria" },
  { label: "categoriaAntt", readable: "Categoria ANTT" },
  { label: "categoriaServicoAntt", readable: "Categoria ANTT" },
  { label: "cargaPerigosa", readable: "Carga Perigosa" },
  { label: "Cobranca Acessoria", readable: "Cobrança Acessória" },
  { label: "contratoAssociado", readable: "Contrato Associado" },
  { label: "condicaoPagamento", readable: "Condição Pagamento" },
  { label: "cnpjCpf", readable: "CNPJ/CPF" },
  { label: "cpfCnpjRaiz_values", readable: "CNPJ/CPF" },
  { label: "cpfCnpjRaiz", readable: "CNPJ" },
  { label: "clienteContrato", readable: "Cliente Principal" },
  { label: "cpfCnpjRaizContrato", readable: "CNPJ Raiz" },
  { label: "carteiraComercial", readable: "Carteira Comercial" },
  { label: "coe", readable: "COE" },
  { label: "codigo", readable: "Código" },
  { label: "codigoMercadoria", readable: "Código" },
  { label: "codigoProduto", readable: "Código" },
  { label: "codigoAntt", readable: "Código ANTT" },
  { label: "codFerroviasParceiras", readable: "Cód. Ferrovias Parceiras" },
  { label: "codFerroviaPartilha", readable: "Ferrovias de Partilha" },
  { label: "codigoDeFerrovia", readable: "Código Ferrovia Parceira" },
  { label: "codLocal", readable: "Cód. Local" },
  { label: "codLocFerrovia", readable: "Sigla Locais Ferrovia" },
  { label: "codVli", readable: "Código VLI" },
  { label: "Codigo de Ferrovia", readable: "Código de Ferrovia" },
  { label: "contribuinte", readable: "Contrib." },
  { label: "contratada", readable: "Contratada" },
  { label: "cnpj", readable: "CNPJ" },
  { label: "servico", readable: "Código/Serviço" },
  { label: "data", readable: "Data" },
  { label: "inicioVigencia_medium", readable: "Início Vigência" },
  { label: "dataInicioVigencia", readable: "Data Base" },
  { label: "dataFimVigencia", readable: "Data Fim" },
  { label: "dataBase", readable: "Data Base" },
  { label: "destino", readable: "Destino" },
  { label: "estacaoDestino", readable: "Destino" },
  { label: "descricao", readable: "Descrição" },
  { label: "descricao_parametros_sistema", readable: "Descrição" },
  { label: "descricaoDetalhada", readable: "Descrição Detalhada" },
  { label: "descricao_medium_size", readable: "Descrição" },
  { label: "descricao_medium_size_active", readable: "Descrição" },
  { label: "descricaoResumida", readable: "Descrição Resumida" },
  { label: "dhInicioVigencia", readable: "Inicio Vigência" },
  { label: "inicioVigencia_values", readable: "Inicio Vigência" },
  { label: "dataInicioVigenciaContrato", readable: "Inicio Vigência" },
  { label: "dhFimVigencia", readable: "Fim Vigência" },
  { label: "dataFimVigenciaContrato", readable: "Fim Vigência" },
  { label: "fimVigencia_values", readable: "Fim Vigência" },
  { label: "Estadia de Vagao", readable: "Estadia de Vagão" },
  { label: "Estacao", readable: "Estação" },
  { label: "estacao", readable: "Estação" },
  { label: "estacaoOrigem_values", readable: "Estação Origem" },
  { label: "estacaoDestino_values", readable: "Estação Destino" },
  { label: "item", readable: "#" },
  {
    label: "estabelecimentosEmitentes",
    readable: "Estabelec. Emitentes (CNPJ - Unidade - Estação)",
  },
  { label: "fatorDeConversao", readable: "Fator Conversão" },
  { label: "fatorConversao", readable: "Fator de Conversão" },
  { label: "fatorConversao_medium_size", readable: "Fator de Conversão" },
  { label: "ferroviaconcessionaria", readable: "Ferrovia Concessionária" },
  { label: "ferrovia", readable: "Ferrovia" },
  { label: "ferrovia_values", readable: "Ferrovia" },
  { label: "ferroviaoperadora", readable: "Ferrovia Operadora" },
  { label: "ferroviaVisitada", readable: "Ferrovia Visitada" },
  { label: "ferroviaVisitante", readable: "Ferrovia Visitante" },
  { label: "Ferrovia Referencia", readable: "Ferrovia Referência" },
  { label: "Ferroviario", readable: "Ferroviário" },
  { label: "ferrovia_servico", readable: "Ferrovia/Serviço" },
  { label: "servico_values", readable: "Serviço" },
  { label: "fimVigencia", readable: "Vig. Final" },
  { label: "historicoProduto", readable: "Histórico" },
  { label: "ibge", readable: "Cod. IBGE" },
  { label: "inicioFaixa", readable: "Início Faixa" },
  { label: "fimFaixa", readable: "Fim Faixa" },
  { label: "inicioVigencia", readable: "Vig. Inicial" },
  { label: "localidade", readable: "Localidade" },
  { label: "mensagem", readable: "Mensagem" },
  { label: "mercadoriaAntt", readable: "Mercadoria ANTT" },
  { label: "mercadoriaAnttModal", readable: "Mercadoria ANTT" },
  { label: "mercadoria", readable: "Mercadoria" },
  { label: "microrregiao", readable: "Microrregião" },
  { label: "modal", readable: "Tipo Modal" },
  { label: "motivoSobreposicao", readable: "Motivo Sobreposição" },
  { label: "municipios", readable: "Municípios" },
  { label: "municipionome", readable: "Município" },
  { label: "nome", readable: "Ferrovia" },
  { label: "nomeFantasia", readable: "Nome Fantasia" },
  { label: "nomeFerrovia", readable: "Nome Ferrovia" },
  { label: "nomeIdentificador", readable: "Nome Identificador" },
  { label: "numeroIdentificador", readable: "Número Identificador" },
  { label: "Outros Servicos", readable: "Outros Serviços" },
  { label: "objeto", readable: "Objeto" },
  { label: "origem", readable: "Origem" },
  { label: "estacaoOrigem", readable: "Origem" },
  { label: "otm", readable: "OTM" },
  { label: "razaoSocialNome", readable: "Razão Social ou Nome" },
  { label: "Rodoviario", readable: "Rodoviário" },
  { label: "responsavel", readable: "Responsável" },
  { label: "Rodoviario", readable: "Rodoviário" },
  { label: "razaoSocialNome", readable: "Razão Social ou Nome" },
  { label: "razaoSocial", readable: "Razão Social Cliente" },
  { label: "razaoSocial_values", readable: "Razão Social" },
  { label: "raizCnpjCliente", readable: "Raiz CNPJ do Cliente" },
  { label: "razaoSocialCliente", readable: "Razão Social do Cliente" },
  { label: "sigla", readable: "Nome" },
  { label: "siglaFerrovia", readable: "Sigla Ferrovia" },
  { label: "status", readable: "Status" },
  { label: "statusContrato", readable: "Status Contrato" },
  { label: "servicoPeso", readable: "Serviço" },
  { label: "servico_min", readable: "Serviço" },
  { label: "parcelaFixa", readable: "Parcela Fixa" },
  { label: "percentualReajuste", readable: "Percentual" },
  { label: "Ponta Rodoviaria", readable: "Ponta Rodoviária" },
  { label: "produto", readable: "Produto" },
  { label: "produto_values", readable: "Produto" },
  { label: "produto_medium", readable: "Produto" },
  { label: "produtoAntt", readable: "Produto ANTT" },
  { label: "quantParcelasVar", readable: "Parcelas Variáveis" },
  { label: "terminal", readable: "Terminal" },
  { label: "Trafego Mutuo", readable: "Tráfego Mútuo" },
  { label: "tipoParametro", readable: "Tipo Parâmetro" },
  { label: "tipoInformacao", readable: "Tipo Informação" },
  { label: "tipoFormalizacao", readable: "Tipo Contrato" },
  { label: "tipoModal", readable: "Tipo Modal" },
  { label: "tipoMicroregiao", readable: "Tipo de Microregião" },
  { label: "tipoServico", readable: "Tipo de Serviço" },
  { label: "tipoVagao", readable: "Tipo Vagão" },
  { label: "tipoPesoServico", readable: "Tipo de Peso do Serviço" },
  { label: "unidadeFederacao", readable: "Unidade Federação" },
  { label: "unidadeMedida", readable: "Unidade de Medida" },
  { label: "unidadesNegocio", readable: "Unidade de Negócio" },
  { label: "valor", readable: "Valor" },
  { label: "valorServico_min", readable: "Valor" },
  { label: "vigFinal", readable: "Vig. Final" },
  { label: "vigInicial", readable: "Vig. Inicial" },
  { label: "valorServico", readable: "Valor de Repasse (R$)" },
  { label: "valorServico_values", readable: "Valor de Repasse (R$)" },
  { label: "uf", readable: "UF" },
  { label: "S", readable: "SIM" },
  { label: "N", readable: "NÃO" },
  { label: "S", readable: "Ativo" },
  { label: "N", readable: "Inativo" },
];

// ? Insert if the item doesnt belong the array, and delete if does.
const decideToIncludeOrDelete = <T>(array: T[], value: T): T[] => {
  const newArray = array;

  if (newArray.includes(value)) {
    const rowIndex = newArray.indexOf(value);
    newArray.splice(rowIndex, 1);
  } else {
    newArray.push(value);
  }

  return [...newArray];
};

export { decideToIncludeOrDelete, readbleArray };
